services:
  - type: web
    name: flood-alert-api
    runtime: docker
    plan: starter
    region: singapore
    healthCheckPath: /health
    envVars:
      - key: SPRING_DATASOURCE_URL
        sync: false
      - key: SPRING_DATASOURCE_USERNAME
        sync: false
      - key: SPRING_DATASOURCE_PASSWORD
        sync: false
      - key: SPRING_DATA_REDIS_URL
        sync: false
      - key: JWT_SIGNEDKEY
        sync: false
      - key: SQL_INIT_MODE
        value: never
      - key: SPRING_JPA_SHOW_SQL
        value: false
