spring.application.name=flood-alert

# Kết nối PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/db_canhbaolulut
spring.datasource.username=postgres
spring.datasource.password=root

# Driver
spring.flyway.driver-class-name=org.postgresql.Driver

# JPA/Hibernate
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# tránh query bậy ở controller, kiểm soát DB tốt hơn
spring.jpa.open-in-view=false


