spring.application.name=flood-alert
server.port=${PORT:8080}

# PostgreSQL
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/db_canhbaolulut}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:postgres}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:root}

# Redis / Render Key Value
spring.data.redis.url=${SPRING_DATA_REDIS_URL:redis://localhost:6379}
# Disable Redis
spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.data.redis.RedisAutoConfiguration 

# Driver
spring.flyway.driver-class-name=org.postgresql.Driver

# JPA/Hibernate
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=${SPRING_JPA_HIBERNATE_DDL_AUTO:update}
spring.jpa.show-sql=${SPRING_JPA_SHOW_SQL:true}
spring.jpa.open-in-view=false
spring.sql.init.mode=${SQL_INIT_MODE:never}
spring.jpa.defer-datasource-initialization=false

# JWT
jwt.signedKey=${JWT_SIGNEDKEY:ca9ef30312c7b8914d59fe00ddd0e60fa427fa3b641ab8791173374f8bec3c86}

spring.jpa.properties.hibernate.jdbc.batch_size=500
spring.jpa.properties.hibernate.order_inserts=true

fastapi.url=https://ai-server-flood-alert.onrender.com

spring.jackson.time-zone=Asia/Ho_Chi_Minh

# Cấu hình mail
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=floodalert.api.demo@gmail.com
spring.mail.password=qlgvpameqgikemmf
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

