spring.application.name=flood-alert
server.port=${PORT:8080}

# PostgreSQL
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/db_canhbaolulut}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:postgres}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:root}

# Redis / Render Key Value
spring.data.redis.url=${SPRING_DATA_REDIS_URL:redis://localhost:6379}

# Driver
spring.flyway.driver-class-name=org.postgresql.Driver

# JPA/Hibernate
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=${SPRING_JPA_SHOW_SQL:true}
spring.jpa.open-in-view=false
spring.sql.init.mode=${SQL_INIT_MODE:never}
spring.jpa.defer-datasource-initialization=false

# logging.level.org.springframework.transaction=DEBUG
# logging.level.org.springframework.orm.jpa=DEBUG

# Nếu database đã có sẵn bảng nhưng chưa từng dùng Flyway,
# tự động tạo baseline để bắt đầu quản lý migration mà không chạy lại các script cũ.
spring.flyway.baseline-on-migrate=true
# Đánh dấu trạng thái hiện tại của database là version 1.
# Các migration mới sẽ bắt đầu từ V2__*.sql trở đi.
spring.flyway.baseline-version=1

# JWT
jwt.signedKey=${JWT_SIGNEDKEY:ca9ef30312c7b8914d59fe00ddd0e60fa427fa3b641ab8791173374f8bec3c86}

spring.jpa.properties.hibernate.jdbc.batch_size=500
spring.jpa.properties.hibernate.order_inserts=true

fastapi.url=https://ai-server-flood-alert.onrender.com

spring.jackson.time-zone=Asia/Ho_Chi_Minh

# Cấu hình mail
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=${MAIL_USERNAME}
spring.mail.password=${MAIL_PASSWORD}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

# Log security: bật log chi tiết của Spring Web, nhằm giúp debug request đang đi đâu
# Log toàn bộ quá trình xử lý Web của Spring:

# Request đến URL nào
# Mapping tới controller nào
# Validation
# Exception
# Response
# logging.level.org.springframework.web=TRACE

# Đây là log của DispatcherServlet (trái tim của Spring MVC).

# Nó sẽ cho biết:

# Request có vào Spring MVC không
# Có tìm thấy Controller không
# Nếu không thì tại sao
# logging.level.org.springframework.web.servlet.DispatcherServlet=TRACE
# Cấu hình SMS
# sms.access-token=${ACCESS}
